version: 0.2
phases:
  install:    
    commands:
      - apt-get update -y
      - apt-get install -y openjdk-11-jdk
      - apt-get install -y maven
  build:
    commands:
      - echo Build started on `date`
      - mvn test 
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/*.war
    - scripts/serverStart.sh
    - scripts/serverStop.sh
    - appspec.yml
  discard-paths: yes